[package]
name = "haddock-restraints"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freesasa-rs = "0.1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pdbtbx = "0.11.0"
rand = "0.8.4"
kd-tree = "0.6.0"
clap = { version = "4.5", features = ["derive"] }
